### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by qbbr**
- rm 2 functions _getPageScroll()_ and _getPageHeight()_
- cleanup code
- updt jQuery to 1.5

### CODE REVIEW

**Comment by kneath** [comment]
Why all the semicolons?

**Comment by qbbr** [comment]
if jsmin delete break line (\n), then JS code  is invalide

false:
`$s.loadingImage = $s.loading_image || $s.loadingImage$s.closeImage = $s.close_image || $s.closeImage`

true:
`$s.loadingImage = $s.loading_image || $s.loadingImage;$s.closeImage = $s.close_image || $s.closeImage;`

**Comment by kneath** [comment]
We've used JSMin and Google Closure on facebox for a long time at GitHub without issue. Are you seeing specific problems? Sounds a lot like conjecture. In any case, I doubt this patch will be accepted — Chris is a pretty big fan of only using semicolons when absolutely necessary (and I have to say I agree).

**Comment by qbbr** [comment]
ok, im rm ';'

**Comment by nzifnab** [comment]
Some browsers (IE...) choke when you don't have semicolons on everything, don't they?  I've always been under the impression semicolons in JS were best-practice and was weirded-out when i didn't see them in facebox.

**Pull request closed without merging**
