### PR TITLE
Allow modal facebox

### PR DESCRIPTION
**Pull request by vincentdieltiens**
I need a facebox that can be modal and that could be only closed when a certain job is done.

A current example is a confirm dialog with two buttons "yes" and "no" and the user must click on one of these two buttons to go back to the "main" page.

I've updated the examples with for the modal but I also have corrected some bugs in the examples.

### CODE REVIEW

**Comment by defunkt** [comment]
You can unbind the close and ESC events:

```
$(document).unbind('facebox')
```

Then close Facebox whenever you want on your own:

```
$.facebox.close()
```

**Comment by vincentdieltiens** [comment]
$(document).unbind('facebox') doesn't do anything...

**Comment by vincentdieltiens** [comment]
And even if $(document).unbind('facebox') works, you have to re-bind 'facebox' event to allow "normal" faceboxes after a modal facebox

**Comment by defunkt** [comment]
Whoops, you're right: `$(document).unbind('.facebox')` or `$(document).bind('.facebox')` will do the trick.

The re-binding thing is a bug that's being addressed in the upcoming facebox2

**Comment by vincentdieltiens** [comment]
The big problem is that you close() method use the event 'close.facebox' :

```
 close: function() {
      $(document).trigger('close.facebox')
      return false
 }
```

I you unbind all facebox events, it's no longer possible to close the facebox...

My $.facebox.modal() do the trick perfectly. Why not merge ?

**Pull request closed without merging**
